### ISSUE TITLE
5000 row limit even when using walk_data=TRUE when qu

### ISSUE THREAD

**Issue by ericbrownaustin** [MarkEdmondson1234/searchConsoleR#10]
When running search_analytics with no dimensions or using the date dimension, my metric counts match what Search Console reports, however, when I add page or query as dimensions, the script only returns 4,999 observations.  Is there still a limitation to the number of observations returned when using either of these dimensions?

![image](https://cloud.githubusercontent.com/assets/11723172/13480856/70e386b6-e0a6-11e5-9c6d-7ddede739706.png)

![image](https://cloud.githubusercontent.com/assets/11723172/13480865/7ae5357e-e0a6-11e5-8341-438f48697d8f.png)

**Comment by MarkEdmondson1234** [comment]
Yes walk only works when date is one of the dimensions at the moment. I'm wondering how to support other dimensions, perhaps add date, walk through the dates, sum it up and remove date? Or just add a condition it's only date.

**Comment by MarkEdmondson1234** [comment]
I have limited the walk_data flag to calls with date included in the dimensions, and added an error message if its not there.

**Comment by ericbrownaustin** [comment]
I'm still only receiving 5,000 rows even when using date as one of the dimensions.  The console also references a 5,000 row limit in the return.  I am using v0.1.2.9002.  Is there something I am doing wrong in my call?

![image](https://cloud.githubusercontent.com/assets/11723172/14150416/8adfc52e-f66e-11e5-93c1-faba9929ac34.png)

![image](https://cloud.githubusercontent.com/assets/11723172/14150449/acdd475a-f66e-11e5-841a-53c233f9e087.png)

![image](https://cloud.githubusercontent.com/assets/11723172/14150468/beb60f34-f66e-11e5-8d3f-ea7337f08e4c.png)
