### ISSUE TITLE
object 'rowLimit0' not found in function search_analytics( ...)

### ISSUE THREAD

**Issue by flovv** [MarkEdmondson1234/searchConsoleR#14]
Using devtools::install_github("MarkEdmondson1234/searchConsoleR")
Other functions seem to work fine.

Here is the error.

> test0 <- search_analytics("http://flovv.github.io/", 
+                           dimensions = c("date","query","page","country"), 
+                           rowLimit = 2000,
+                           walk_data = "byBatch")
Fetching search analytics for url: http://flovv.github.io/ dates: 2016-02-29 2016-05-29 dimensions: date query page country dimensionFilterExp:  searchType: web aggregationType: auto
Error in seq.default(0, rowLimit0, 5000) : object 'rowLimit0' not found

**Comment by eluerken** [comment]
I have the same issue:
```
search_analytics("http://www.XXXXXXXX.com", 
+                      c("query", "page"), 
+                      searchType="web", rowLimit = 100)
Fetching search analytics for url: http://www.XXXXXXXXXXX.com dates: 2016-03-19 2016-06-17 dimensions: dimensionFilterExp: searchType: web aggregationType: auto
Error in seq.default(0, rowLimit0, 5000) : object 'rowLimit0' not found
```
In addition to this, I've manually defined rowLimit0 manually, which resolves the first issue, but then I get this
```
Fetching search analytics for url: https://www.prepsportswear.com dates: 2016-03-19 2016-06-17 dimensions:  dimensionFilterExp:  searchType: web aggregationType: auto
Warning message:
In f(content, ...) : No data found
```

**Comment by MarkEdmondson1234** [comment]
Thanks for the reports! This is fixed now on github.  There is no need to set the batch flag when under 5000 rows, but it was defaulting to being turned on when it shouldn't.
