### ISSUE TITLE
top 20 keywords 

### ISSUE THREAD

**Issue by prasoonsrivas** [MarkEdmondson1234/searchConsoleR#15]
Having the excel sheet containing list of keywords, from that top 20 keywords want to extract the landing page , Ctr ,position like that for weekly basis from the webmaster . how to do it 

Any help will be appreciated . 

Thanks

**Comment by MarkEdmondson1234** [comment]
I would do something like importing all your keywords into R (its easier if you export your keywords via CSV) so you have your keywords to compare with the search console downloads.

Then download all the keywords in search console R, and do a match.  Pseudo code something like:

```r
imported_keywords <- read.csv("your_keywords.csv")
library(searchConsoleR)
scr_auth()
sc_data <- search_analytics("your-website.co.uk", 
                        start = Sys.date() - 10, end = Sys.date() - 3, 
                        dimensions = c("query", "page"))

## filter sc_data to your keywords
output <- sc_data[sc_data$query %in% imported_keywords, ]
```

**Comment by prasoonsrivas** [comment]
Mark Thanks a lot for your support , but i need only that landing page which has highest clicks on that day for that keyword, 

your help is appreciated.

**Comment by MarkEdmondson1234** [comment]
I don't quite get what you mean, but you could modify the above to include "date" like so:

```r
scr_auth()
sc_data <- search_analytics("your-website.co.uk", 
                        start = Sys.date() - 10, end = Sys.date() - 3, 
                        dimensions = c("query", "page"))
```

...which you can then filter and sort to find the highest clicks for any query and landing page.

**Comment by prasoonsrivas** [comment]
Hi Mark 

Complete story :-  I am having a set of keywords category wise  in CSV file (means suppose Hard disk will fall in category of Electronics , Electronic chimney will falls in category of Home appliances like that ) now i am taking one keyword from one category searching it in search console within a date range 
and if it is there it will return the Landing page , date , query, clicks,CTR,Impressions .......
Note: Time frame is One week(06-19-2016 to 06-25-2016)

The problem is that after getting the data suppose on 06-19-2016 for Hard Disk keywords 

Landing page https://www.abc.com/cd/adc/adcf.html
Hard Disk
Clicks 37
Impression 442
CTR 0.083710407
POosition 5.042986

Landing page https://www.zbc.com/cd/adc/asd.html
Hard Disk
Clicks  2
Impression 48
CTR   0.041666667
POosition 4.833333

  I need that landing page of the keyword which has max clicks for that date suppose on 06-19-2016
and if keywords is not in search result return the NA for that key word

Sample Code :--------------------

end <- Sys.Date()-4

start <- Sys.Date()-10

## choose between data, query, page, device, country
download_dimensions <- c('date','page','query')

## choose between 'web', 'video' or 'image'
type <- c('web')

bike_comp <- data.frame()

c <- length(unique(keywords$Family))-1

for (i in 1:c)
{
  dimfil <- paste('query==',keywords$Family[i],'',sep='')
  
  
  loop <- search_analytics(siteURL = website, 
                           startDate = start, 
                           endDate = end, 
                           dimensions = download_dimensions, 
                           searchType = type,
                           dimensionFilterExp = dimfil,
                           walk_data = TRUE)
  
  
  bike_comp <- rbind(loop,bike_comp)  
  
}

**Comment by MarkEdmondson1234** [comment]
I suggest you download all the keywords, date and pages with no filter (loop over some dates if you need to) then apply your filters within R afterwards for what you need.  I would suggest using `dplyr` or similar to merge your keywords with the categories, then group the table into categories and sort within them to find what you are after.  For instance 

```r
library(dplyr)
your_data %>% left_join(your_categories, by = "keyword") %>% group_by(categories, date) %>% arrange(desc(clicks))

```

It sounds more like a general how to use R issue than a problem with the library itself, so I'll keep this issue closed, but suggest also that if you have further problems get some sample data and what you have tried so far and post on StackOverflow as you'll get quicker and better response there than just little old me here :)
