### ISSUE TITLE
Raise an error if fetching with no authentication

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/searchConsoleR#23]
Its confusing if there is no authentication and it still attempts to fetch with NAs as the result

**Comment by j450h1** [comment]
@MarkEdmondson1234  Is this still relevant now that there is a new method for authentication using gargle? If so, please do point me in the right direction and I can take a crack at it.

**Comment by MarkEdmondson1234** [comment]
It could be, could you run a test? I think I covered it though.


________________________________

**Comment by MarkEdmondson1234** [comment]
Yes it’s covered via

if(!googleAuthR::gar_has_token())

can close this issue


________________________________

**Comment by j450h1** [comment]
You know me..just hunting for some good ole Hactoberfest PRs this time of year :) . Feel free to suggest any Issues you think I might be a good fit for.
