### ISSUE TITLE
list_crawl_error_samples - trouble with list of multiple URLs

### ISSUE THREAD

**Issue by johnschoofs** [MarkEdmondson1234/searchConsoleR#25]
Hello - 

I am trying to create a meaningful report from the function in the title.  The challenge I am having is with the final column of data (a list) which are the linked from URLs.  The format it returns data in right now would be like this generic example: 

```
Col1   Col2
dog    c("black lab", "chocolate lab")
```
I would like it to be: 

```
Col1   Col2  
dog    black lab
dog    chocolate lab
```

Could anyone provide me help?  I've searched on stackoverflow and had no success.  Thank you.

**Comment by MarkEdmondson1234** [comment]
Its a bit deceptive as it looks like a data.frame, but its not really in a nice format, with nested data.frames etc. :

```r
library(searchConsoleR)
scr_auth()

my_website <- "http://example.com"
lces <- list_crawl_error_samples(my_website)
> str(lces)
'data.frame':	23 obs. of  5 variables:
 $ pageUrl       : chr  "error-404.aspx?aspxerrorpath=/home/about-us/press-releases/fact-files/bob.aspx" "home/trav" "home/bob-a-risk-factor-for-11-canc" "error-404.aspx?aspxerrorpath=/ScriptResource.axd" ...
 $ last_crawled  : POSIXlt, format: "2017-04-25 18:08:03" "2017-04-27 13:39:33" "2017-04-23 04:51:05" "2017-04-23 18:20:46" ...
 $ first_detected: POSIXlt, format: "2016-11-28 06:01:04" "2017-04-27 13:39:33" "2017-04-23 04:51:05" "2017-04-23 18:20:46" ...
 $ responseCode  : int  404 404 404 404 404 404 404 404 404 404 ...
 $ urlDetails    :'data.frame':	23 obs. of  1 variable:
  ..$ linkedFromUrls:List of 23
  .. ..$ : chr "https://www.example.co.uk/home/about-us/press-releases/fact-files/shelley-fletcher.aspx"
  .. ..$ : NULL
  .. ..$ : chr  "https://es.f
```

I will look at improving the output format, but for now I suggest using list columns as outlined in the tidyverse here: https://jennybc.github.io/purrr-tutorial/ls13_list-columns.html

I approach it like the below, perhaps can be improved:

```r
library(tibble)
library(purrr)
library(dplyr)
library(tidyr)

## make named list of the linkedFromURls and pageUrl:
linked_urls <- lces$urlDetails$linkedFromUrls
linked_urls <- setNames(linked_urls, lces$pageUrl)

## use tibble's enframe to turn list into tibble data.frame with list columns:
linked_urls <- tibble::enframe(linked_urls, name = "pageUrl", value = "linkedFromUrls")

## turn linked URLs into a single string seperated by ","
## then expand out each URL into its own column
final <- linked_urls %>% 
  mutate(urls = purrr::map_chr(linkedFromUrls, paste, collapse = ",")) %>% 
  tidyr::separate(urls, into = paste0("url", 1:10), sep = ",", fill = "right")

```

You then have the URL on your website in `final$pageUrl` and a column for each example external URL in respective columns, up to 10. (`final$url1, final$url2, ...`)  If not present the column is `NA`

**Comment by johnschoofs** [comment]
Hi @MarkEdmondson1234  

Your solution is perfect.  Thank you!  

Now that you've got me on the right track, let me work with it and see if I may be able to propose a means for improvement.  Thank you for this great package.  I have really seen a lot of value from it.
