### ISSUE TITLE
In data_parse_function(req$content, ...) : No data found

### ISSUE THREAD

**Issue by googlogmob** [MarkEdmondson1234/searchConsoleR#27]
Hi
I got this code here in Issues 

```r
site <- "http://digitl-laboratory.96.lt/"

start <- as.character(Sys.Date() - 30)
end <- as.character(Sys.Date() - 3)

scData <- search_analytics(
  siteURL = site,
  startDate = start,
  endDate = end,
  dimensions = c("date", "query")
)
```

Executing this code i got such error:

```r
> Fetching search analytics for url: http://digitl-laboratory.96.lt/ dates: 2017-06-06 2017-07-03 dimensions: date query dimensionFilterExp:  searchType: web aggregationType: auto
Warning message:
In data_parse_function(req$content, ...) : No data found
```

Using this option
```r
options("googleAuthR.rawResponse" = TRUE)

scData <- search_analytics(
siteURL = site,
startDate = start,
endDate = end,
dimensions = c("date", "query")
)
scData
```

appears error message

```
    Error : $ operator is invalid for atomic vectors
    Warning message:
    In search_analytics_g(the_body = body, path_arguments = list(sites = siteURL), :
    API Data failed to parse. Returning parsed from JSON content.
    Use this to test against your data_parse_function.
    scData
    NULL
```

Please, solve how to correct mistake

**Comment by googlogmob** [comment]
Using this option
`**options("googleAuthR.rawResponse" = TRUE)**

scData <- search_analytics(
  siteURL = site,
  startDate = start,
  endDate = end,
  dimensions = c("date", "query")
)
scData`

appears error message

> Error : $ operator is invalid for atomic vectors
Warning message:
In search_analytics_g(the_body = body, path_arguments = list(sites = siteURL),  :
  API Data failed to parse.  Returning parsed from JSON content.
                    Use this to test against your data_parse_function.
> scData
NULL

**Comment by MarkEdmondson1234** [comment]
Can you run `list_websites()`?  I think you may not be authenticated.

**Comment by googlogmob** [comment]
list_websites() works fine
> list_websites()

 `siteUrl permissionLevel`
`http://digitl-laboratory.96.lt/    siteFullUser`

**Comment by MarkEdmondson1234** [comment]
Hmm I really don't know then, are you positive this URL has data in the search console for these dates?  Sometimes you need to use `www` or `https` specifically.

**Comment by googlogmob** [comment]
You are right
all indicators are null
http://prntscr.com/fsizc0

Thanks
