### ISSUE TITLE
DataFrame Contents only returns 1 object instead of all compared to sitemap DF

### ISSUE THREAD

**Issue by MartijnSch** [MarkEdmondson1234/searchConsoleR#29]
https://github.com/MarkEdmondson1234/searchConsoleR/blob/06f182a53b1c10569a095d1562532410907bcb7d/R/reqParse.R#L69

**Comment by MarkEdmondson1234** [comment]
Thanks for the report!  This is fixed on the GitHub version, but not on CRAN yet - to install:

```r
devtools::install_github("MarkEdmondson1234/searchConsoleR")
```

**Comment by MartijnSch** [comment]
Thanks Mark!
