### ISSUE TITLE
Problems in batch processing with googleAuthR 0.6

### ISSUE THREAD

**Issue by fj-adm** [MarkEdmondson1234/searchConsoleR#34]
Hi,
I have issues using the batch function.
non-batch queries are fine.

```
test0 <- search_analytics(page, 
                          dimensions = c("date","query","page","country"), 
                          rowLimit = 20000, 
                          walk_data = "byBatch")

1: In doBatchRequest(l) :
  Deprecated batch endpoint being used.  Use option('googleAuthR.batch_endpoint') 
            to select specific endpoint for this API.
```
byDate results in very small tables with <5000 rows for a very large site.

**Comment by MarkEdmondson1234** [comment]
The message is just a warning and it should complete as before the update to `googleAuthR 0.6.0`, so shouldn't affect things like number of results returned.  Soon the GitHub version will update the batch endpoint and the warning will go, but that should be the only effect.

But if you can reproduce a difference, do let me know!

**Comment by MarkEdmondson1234** [comment]
I can confirm this, for now you can roll back to googleAuthR 0.5.1 by using this:

```
devtools::install_github("MarkEdmondson1234/googleAuthR@v5.1")
```

I will take a look at why its done it.

**Comment by MarkEdmondson1234** [comment]
Ok I think I got it fixed now, if you install the latest `googleAuthR` from GitHub:

```
devtools::install_github("MarkEdmondson1234/googleAuthR")
```

**Comment by fj-adm** [comment]
Hi Mark, 
thanks for the fix and your excellent work.
Everything works fine now!
