### ISSUE TITLE
Fails to install/update

### ISSUE THREAD

**Issue by chicofish** [MarkEdmondson1234/searchConsoleR#35]
Today I am getting errors while trying to batch byDate for over 5000 records on code that worked properly a month ago.  While debugging, I tried installing an update (RStudio, Windows, R 3.4) and it won't install, unable to create lock directory.  I then manually deleted the package and tried installing.  No joy.  I've tried installing from GitHub, from source, download local copy and install and it keeps giving me permission denied errors.

I am, however, able to download and install various other packages.

Thanks

**Comment by MarkEdmondson1234** [comment]
Weird, are you able to show the code that errors now with what message you are getting? Also please show the results of sessionInfo(). 

It just released a new version to CRAN today, so perhaps you caught it in between updates.

**Comment by chicofish** [comment]
> install.packages("searchConsoleR")
Installing package into ‘\\cdc.gov/private/M311/xxxx/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.4/PACKAGES.rds': HTTP status was '404 Not Found'

  There is a binary version available but the source version is later:
               binary source needs_compilation
searchConsoleR  0.2.1  0.3.0             FALSE

installing the source package ‘searchConsoleR’

trying URL 'https://cran.rstudio.com/src/contrib/searchConsoleR_0.3.0.tar.gz'
Content type 'application/x-gzip' length 36202 bytes (35 KB)
downloaded 35 KB

'\\cdc.gov\private\M311\xxxx'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
Warning in dir.create(lockdir, recursive = TRUE) :
  cannot create dir '\\cdc.gov\private\M311', reason 'Permission denied'
ERROR: failed to create lock directory '\\cdc.gov/private/M311/xxxx/R/win-library/3.4/00LOCK-searchConsoleR'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" CMD INSTALL -l "\\cdc.gov\private\M311\xxxx\R\win-library\3.4" C:\Users\evp9\AppData\Local\Temp\1\RtmpKAwz7o/downloaded_packages/searchConsoleR_0.3.0.tar.gz' had status 3
Warning in install.packages :
  installation of package ‘searchConsoleR’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\xxxx\AppData\Local\Temp\1\RtmpKAwz7o\downloaded_packages’


sessionInfo()

R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.0 tools_3.4.0

**Comment by chicofish** [comment]
Upon deeper testing, anything I'm installing from GitHub sources fail.  So I'll have to wait for the windows binary to be available on CRAN or fix this permission issue that came up probably from a Windows security patch.

Any idea when the Windows binary will be available on CRAN?

Thanks

**Comment by MarkEdmondson1234** [comment]
I got a message the binary was built this morning, so I guess it needs to propagate to the mirrors. Your one looks like it’s a 404, you could try the RStudio one.

**Comment by chicofish** [comment]
There is joy in Muddville!  Binary finally downloaded and installed.  I'll close this ticket.

Thanks
