### ISSUE TITLE
search_analytics Google Search Console - SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by manuelgomezrico** [MarkEdmondson1234/searchConsoleR#38]
Hi, I´m using this package and all right. But today I´m trying to get information and I have this error:
**Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL certificate problem: self signed certificate in certificate chain
Request failed before finding status code: SSL certificate problem: self signed certificate in certificate chain**
I have spent a lot time and I don´t know what happens
Any idea?
This web is http://www.x.com. Could be the problem this url not is https?
My user is owner the this website in Google Console Search
Thank so much

**Comment by MarkEdmondson1234** [comment]
Are you on windows?  I suspect this is to do with the https API requests in curl.  Try updating your `curl` dependency package, and follow the advice on this thread where a similar issue got solved https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/123

**Comment by MarkEdmondson1234** [comment]
Could you also report your `sessionInfo` as I thought this was fixed in latest version of `googleAuthR 0.6.2`

**Comment by manuelgomezrico** [comment]
Yes, is windows!! Also I have version googleAuthR 0.6.2
I will read the thread that you tell me
Thanks :)

**Comment by manuelgomezrico** [comment]
You have a reason, I have updated curl dependency package and all ok!! Thanks for are always here!!

**Comment by MarkEdmondson1234** [comment]
Great :)
