### ISSUE TITLE
Error in lookupCountryCode

### ISSUE THREAD

**Issue by fcattai** [MarkEdmondson1234/searchConsoleR#5]
Hi there!

after installing searchConsoleR directly in Rstudio (on a MAC), I tried this query:
```
website <- #my website address
start <- Sys.Date() - 3
end <- Sys.Date()
download_dimensions <- c('date','country','device','page','query')
type <- c('web')

gar_auth()

ga.data <- search_analytics(siteURL = website, 
                         startDate = start, 
                         endDate = end, 
                         dimensions = download_dimensions, 
                         searchType = type)
```
and the result is this error:
```
Error in lookupCountryCode(dimensionCols$country) : 
  country.code not in country.codes. Got: ITAITAITAITAGBRRUSITARUSITADEUITADEUITAITAITARUSITACHEITARUSITAUKRITARUSRUSUKRITAITAUKRRUSITARUSCXXUKRITADEUITA
```

Then I installed searchConsoleR from GitHub, and it seems more "tolerant" since I get the same error but the dataframe at the end is correctly created in Rstudio. This is the message:
```
Warning messages:
1: In lookupCountryCode(dimensionCols$country) :
  country.code not in country.codes. Got: ITAITAGBRITAITAITARUSDEUUKRDEUITAUKRRUSITARUSITAITACXXITARUSITAITAITAUKRUKRITADEUITARUSCHERUSITARUSITARUSITAITA
2: In lookupCountryCode(dimensionCols$country) :
  Returning original country.code instead.
```
Afther comparing the 3 letter code of the dataframe with the 3 letter code from the package ISOcodes on the table data("ISO_3166_1"), maybe the problem is on this 3 letter code "CXX".

```
library(ISOcodes)
data("ISO_3166_1")
ISO_3166_1 <- ISO_3166_1[c("Alpha_3", "Name")]
unique(ga.data$countryName)[!unique(ga.data$countryName) %in% unique(ISO_3166_1$Alpha_3)]
```

This "CXX" appears in data from Google, but it is not on ISO_3166_1$Alpha_3

maybe I'm missing something, but I'd like to know if it is a bad use of searchConsoleR or it is a real bug.

hope this help you in developing searchConsoleR.

thanks!

**Comment by MarkEdmondson1234** [comment]
Thanks for reporting this, I could replicate it here myself and fixed the bug. If you load the github version of the package it should now work for you too.  To do that, run:

```
## if you haven't the package devtools, install it:
install.packages("devtools")

## install dev version of package.
devtools::install_github("MarkEdmondson1234/searchConsoleR")
library(searchConsoleR)
```

**Comment by MarkEdmondson1234** [comment]
And incidentally, it looks like there is a bug with the Google's API too, as `CXX` isn't on the ISO list.  Perhaps they mean Christmas Island (`CXR` ?)  

Seems weird we both got traffic from there through.  anyhow, now if we find a country code we don't recognise it won't stop and error, but raise a warning and return the code again so you can at least see the data.

**Comment by fcattai** [comment]
thanks!
Just for understanding the problem: I tried to replicate in search console web interface an API query that shows CXX as country code. In my case on 2015-09-09 there is a result with country code CXX.

this is what web interface shows:
![image](https://cloud.githubusercontent.com/assets/10104796/9835963/968e7bec-5a04-11e5-8ccd-dd3554079d60.png)

and this is what the same query returns with API:

![image](https://cloud.githubusercontent.com/assets/10104796/9835968/c80c3286-5a04-11e5-817e-c84cb87676e9.png)

It seems very clear that CXX stands for "Unknown Region": so with the last update of searchConsoleR it is very easy to manage this API issue.
