### ISSUE TITLE
How to query sc-domain?

### ISSUE THREAD

**Issue by danielkupka** [MarkEdmondson1234/searchConsoleR#53]
Hi, 

I saw that you support sc-domain but get an error message:

default_fetch <- search_analytics("sc-domain:example.com")

Error in check.Url(siteURL, reserved = T) : 
  URL must include protocol, e.g. http://example.com

Thanks for your help and the great package. 
Best

**Comment by MarkEdmondson1234** [comment]
Hi, have you downloaded the latest version from GitHub?

**Comment by danielkupka** [comment]
Yeah, that was the reason. Works! Can be closed.
