### ISSUE TITLE
Get data from a domain property

### ISSUE THREAD

**Issue by prischini** [MarkEdmondson1234/searchConsoleR#56]
Hi there!
I'm trying to get Google Search Console data for a domain property.
When I launch the script I've got this error:

error in check.Url(siteURL, reserved = T) : 
  URL must include protocol, e.g. http://example.com - got:sc-domain:mydomain.com

even if I'm using  sc-domain:mydomain.com as indicated by the SC API documentation.

This is the function I'm using:

search_analytics(siteURL, startDate = Sys.Date() - 93, endDate = Sys.Date() - 3, dimensions = NULL, searchType = c("web", "video", "image"), dimensionFilterExp = NULL, aggregationType = c("auto", "byPage", "byProperty"), rowLimit = 1000, prettyNames = TRUE, walk_data = c("byBatch", "byDate", "none"))

Thanks in advance

paolo

**Comment by MarkEdmondson1234** [comment]
Which version are you using? Can you check via sessionInfo()?

**Comment by prischini** [comment]
Hi Mark,
thanks for the quick reply.
I'm using the 0.3.0.

**Comment by MarkEdmondson1234** [comment]
You need version 0.4.0


________________________________
