### ISSUE TITLE
Problem online app with scr_auth()

### ISSUE THREAD

**Issue by lucamagni** [MarkEdmondson1234/searchConsoleR#59]
## What goes wrong
Hi Mark.
Thankyou for this awesome package in R.

I have a question about deploy my app online.
In my app I want log in with Google for analyze both Google Analytics and Google Search Console; I have set all options required and upload the JSON file I have download in my Google Developer page. I used javascript login function (googleAuth_js).

When I try in my local environment all works as I expected.
But when I try to run online, when I call search_analytics function, the result is:
**Not authenticated. Run scr_auth()**

## Expected output

Request: https://www.googleapis.com/webmasters/v3/sites/
Fetching search analytics for url:  dates: 2020-02-11 2020-05-11 dimensions: query page country device dimensionFilterExp:  searchType: web aggregationType: auto

## Actual output
options(googleAuthR.scopes.selected=c('https://www.googleapis.com/auth/analytics.readonly','https://www.googleapis.com/auth/webmasters.readonly'))
options(googleAuthR.client_id='XXXXX.apps.googleusercontent.com')
options(googleAuthR.client_secret='XXXXXX')
options(googleAuthR.webapp.client_id='XXXXX.apps.googleusercontent.com')
options(googleAuthR.webapp.client_secret=' XXXXX')

_Note that client_id is different from webapp.client_id, because I have two apps in my Google Console, one with type "Other", and one for type "web application"_

Warning: Error in : Not authenticated. Run scr_auth()

## Session Info

other attached packages:
 [1] Rfacebook_0.6.15        httpuv_1.5.2            rjson_0.2.20
 [4] httr_1.4.1              searchConsoleR_0.4.0    googleAnalyticsR_0.7.1
 [7] googleAuthR_1.2.1       shinycustomloader_0.9.0 sodium_1.1
[10] shinyjs_1.1             shinyauthr_0.1.0        data.table_1.12.8
[13] stringr_1.4.0           lubridate_1.7.8         plotly_4.9.2.1
[16] ggplot2_3.3.0           DT_0.13                 dplyr_0.8.5
[19] shinydashboard_0.7.1    shiny_1.4.0.2

**Comment by MarkEdmondson1234** [comment]
I think you are missing a `googleAuthR::gar_auth()` call after you have set the client_id options etc.  There is an example on the googleAuthR website https://code.markedmondson.me/googleAuthR/articles/google-authentication-types.html#multiple-authentication-tokens

`scr_auth()` wraps the `googleAuthR::gar_auth()` function and only authenticates with Search Console, so you need `gar_auth()` to authenticate with both after you've done your setup.

**Comment by lucamagni** [comment]
Yes, you're right. I think that in my local environment I have follow the steps for gar_auth() but not in online application (because unfortunately in my Linux server I run the app with shiny::runApp() and when try to open browser for authentication, in console I see "Waiting for open browser", but nothing happen, so I can't finish steps of gar_auth() function.. instead Google Analytics library use js auth and I can achieve the goal).
Thank you for your support, I try to find a solution for that

**Comment by MarkEdmondson1234** [comment]
Ok in that case you are in non-interactive authentication territory, which I recommend you do via a service account if you do not need other users to login and use their own data.   Get a service key and put its email as a user in GA and Search Console, then you can authorize without needing a browser.  

References:

https://code.markedmondson.me/googleAuthR/articles/google-authentication-types.html#authentication-with-a-json-file-via-service-accounts
https://cran.r-project.org/web/packages/gargle/vignettes/non-interactive-auth.html

**Comment by lucamagni** [comment]
Thanks Mark very helpful!
I follow your suggestions
