### ISSUE TITLE
Function check.Url doesn't allow queries of android apps

### ISSUE THREAD

**Issue by carlosestevez** [MarkEdmondson1234/searchConsoleR#7]
Hi @MarkEdmondson1234, I've noticed that when you try to get data from an android app function check.Url doesn't allow it, because it checks the url starts with http.

As Search Console also supports android apps, this check should be:

grepl("(http|android-app)",url)

Thank you very much for your work on this library, it's really useful!

**Comment by MarkEdmondson1234** [comment]
Thanks @carlosestevez !  Good catch, I have no android apps to test against so thanks for that. I'll put it in.

**Comment by carlosestevez** [comment]
YW @MarkEdmondson1234 :)

**Comment by MarkEdmondson1234** [comment]
Hi @carlosestevez or anyone with an android app, this is now implemeted in https://github.com/MarkEdmondson1234/searchConsoleR/commit/8ab984cdc0c9469cd1db9a6746edc8bd6540448b

Could you test it to see if its in correctly?

**Comment by carlosestevez** [comment]
Hi @MarkEdmondson1234, it works smoothly :)

Thanks!

**Comment by MarkEdmondson1234** [comment]
Great, thanks - will be on CRAN soon
