### ISSUE TITLE
New discover feature

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/searchConsoleR#72]
Add this https://developers.google.com/search/blog/2021/10/search-analytics-discover-gnews

**Comment by MarkEdmondson1234** [comment]
Thanks @eatom  - I missed a bit as you say.  Try it now?

**Comment by eatom** [comment]
> Thanks @eatom - I missed a bit as you say. Try it now?

Thanks @MarkEdmondson1234 , it is working now 👍
