### ISSUE TITLE
API Data failed to parse - improve message when no rows in return data

### ISSUE THREAD

**Issue by SimonHasager** [MarkEdmondson1234/searchConsoleR#8]
Hi @MarkEdmondson1234 , Hope your'e well. Everything worked just fine the other day but now I keep getting this error when running `search_analytics()`:

`Warning message:
In search_analytics_g(the_body = body, path_arguments = list(sites = siteURL),  :
  API Data failed to parse.  Returning raw content.  
                    Use this to test against your data_parse_function.`

However, `list_websites()` still works fine and returns a full list of SC websites... Can you help me out?

**Comment by MarkEdmondson1234** [comment]
Hi Simon, mine is working fine - could you show me a bit of your code which triggers the error?  Also make sure you are using the CRAN versions of searchConsoleR and googleAuthR.  My test code:

    library(searchConsoleR)
    scr_auth()
    list_websites()
    search_analytics("http://www.example.com", startDate = "2016-01-01", endDate="2016-01-28")

That error message comes when the API call worked but the parsing of the response fails.  The object should hold something, if you can do a `str(your_error_fetch)` then that can help deparse it too.

Hope all is well!

**Comment by SimonHasager** [comment]
Thanks, Mark! It seems to work again now but I'm not sure why. This is an example of my script:

`### SETUP

## Set working directory
setwd('C:/...')

## Clean environment
rm(list=ls())

## Load libraries or download if necessary
if(!require(devtools)){install.packages("devtools")}
library(devtools)
if(!require(curl)){install.packages("curl")}
library(curl)
if(!require(lubridate)){install.packages("lubridate")}
library(lubridate)
if(!require(googleAuthR)){devtools::install_github("MarkEdmondson1234/googleAuthR")}
library(googleAuthR)
if(!require(googleAnalyticsR)){devtools::install_github("MarkEdmondson1234/googleAnalyticsR_public")}
library(googleAnalyticsR)
if(!require(searchConsoleR)){install.packages("searchConsoleR")}
library(searchConsoleR)

## Authenticate with Google APIs

# My googleAuthR client
options("googleAuthR.client_id" = "CLIENT_ID")
options("googleAuthR.client_secret" = "CLIENT_SECRET")
options("googleAuthR.scopes.selected" = c(
  "https://www.googleapis.com/auth/analytics",
  "https://www.googleapis.com/auth/webmasters"
  )
)

# My googleAnalyticsR client
options("googleAnalyticsR.webapp.client_id" = "CLIENT_ID")
options("googleAnalyticsR.webapp.client_secret" = "CLIENT_SECRET"")

# My searchConsoleR client
options("searchConsoleR.client_id" = "CLIENT_ID")
options("searchConsoleR.client_secret" = "CLIENT_SECRET"")

## Create .httr-oauth file the first time
# gar_auth(new_user=TRUE)

## Read .httr-oauth file
gar_auth()
# scr_auth()

## Set Google Analytics viewID and Search Console siteURL
viewID <- 12345678
site <- "http://www.example.com/"

## Set date range
start <- as.character(Sys.Date() - 3)
end <- as.character(Sys.Date() - 3)


### FETCH

gaData <- google_analytics(
  viewID,
  start = start,
  end = end,
  metrics = c("sessions"),
  dimensions = c("date"),
  samplingLevel = "WALK"
)

scSites <- list_websites()

scData <- search_analytics(
  siteURL = site,
  startDate = start,
  endDate = end,
  dimensions = c("date", "query")
)`

It seems like it's only working with dev version of googleAuthR (not CRAN) and both with `gar_auth()` and `scr_auth()`--what's the difference? :-)

**Comment by MarkEdmondson1234** [comment]
The dev version and CRAN version are the same now. 0.2.0.  Would you also mind show which versions of the packages you are using?

    sapply(c("googleAuthR", "searchConsoleR", "googleAnalyticsR"), packageVersion)

**Comment by SimonHasager** [comment]
Sure:
```
> sapply(c("googleAuthR", "searchConsoleR", "googleAnalyticsR"), packageVersion)
$googleAuthR
[1]    0    1    1 9003

$searchConsoleR
[1]    0    1    2 9001

$googleAnalyticsR
[1]    0    0 9001
```

**Comment by SiegHartR** [comment]
Hi Mark, I have a similar error running my R script.
Error in SAData(my_site, my_keyword[i]) : 
  incorrect number of dimensions
In addition: Warning message:
In search_analytics_g(the_body = body, path_arguments = list(sites = siteURL),  :
  API Data failed to parse.  Returning raw content.
                    Use this to test against your data_parse_function.
>

I made a function called SAData which uses search_analytics()

SAData    <- function (website, word) {
  
  MyData <- search_analytics(website, 
                                                start_date, 
                                                end_date, 
                                                dimension = "query",
                                                dimensionFilterExp = paste0("query==", word), 
                                                searchType = "web", 
                                                rowLimit = 5000) 
  return(MyData)
}

Using Search Console I found out this error raises when no data is found in Search Analytics (i.e. when shows the following message: "There is no data for this set of filters."

For all the other queries with some results in Search Analytics works.

Any idea or suggestion?

Thanks

**Comment by MarkEdmondson1234** [comment]
Hi SiegHartR aka Nicolino :)

First I should update the error message when its empty, to give a better idea for you and others whats going on.

But practically, I would suggest wrapping the function in a `try()`clause, so you get something to work with even if it fails, something like:

```
## I use these error functions a lot in my projects for convenience
is.error <- function(test_me){
  inherits(test_me, "try-error")
}

error.message <- function(test_me){
  if(is.error(test_me)) attr(test_me, "condition")$message
}

## your code modified to return a NULL when the search_analytics call fails:
SAData    <- function (website, word) {

  MyData <- try(search_analytics(website, 
                             start_date, 
                             end_date, 
                             dimension = "query",
                             dimensionFilterExp = paste0("query==", word), 
                             searchType = "web", 
                             rowLimit = 5000))

  if(is.error(MyData){
    message("Error in fetch, returning NULL")
    MyData <- NULL

  }
  return(MyData)
}
```

**Comment by SiegHartR** [comment]
Thanks Mark for your message.

I tried once with a try() and something similar and now with your suggestion (which is great and simple), but unfortunately it's still raising the same exact error.

Any other idea?

Sorry and thanks again.

**Comment by MarkEdmondson1234** [comment]
Could you share the exact code? The try statement should mean any error is ignored (but still print a message)

**Comment by SiegHartR** [comment]
I use this for loop to get all the data from a combined list of keywords, and when it should reach a NULL statement write "no data" for each option in Search Analytics, but instead stops when no data is found and pops up that error message. 

for (i in 1:length(my_keyword)) { 
  
  kw_data <- SAData(my_site, my_keyword[i])[1,2:5]
  
  if (!is.null(ikw_data)) {
    colnames(kw_data) <- paste(my_keyword[i], colnames(kw_data), sep = "_")
    Overview <- cbind(Overview, kw_data)
  } else {
    kw_data <- data.frame(matrix(vector(), 0, 4, dimnames=list(c(), c(paste0(my_keyword[i], "_clicks"), 
                                                                          paste0(my_keyword[i], "impressions"), 
                                                                          paste0(my_keyword[i], "_ctr"), 
                                                                          paste0(my_keyword[i], "_position") 
    ))), stringsAsFactors=FALSE)
    
    kw_data[1, ] <- c("no data", "no data", "no data", "no data")
    Overview <- cbind(Overview, kw_data)
  }
}

**Comment by MarkEdmondson1234** [comment]
Try installing from github now, I've updated what happens if there are no results to return.

**Comment by SiegHartR** [comment]
Great Mark!

Now works, I get NA values with my for loop, which I just need to sort it.

Many thanks.

**Comment by lcmercado** [comment]
Just FYI for fellow users out there, Google Search Console seems to be stuck since February 23. So no data will be retrieved from that date on until issue is fixed.
