### ISSUE TITLE
searchConsoleR was removed from CRAN; WebTechnology Task View

### ISSUE THREAD

**Issue by wibeasley** [MarkEdmondson1234/searchConsoleR#85]
@cpsievert, I'm a maintainer of the [WebTechnology Task View](https://cran.r-project.org/web/views/WebTechnologies.html).  It looks like [your package was recently removed from CRAN](https://github.com/cran-task-views/WebTechnologies/issues/529).  

1. Do you have any plans to resubmit it?
2. If we remove it from the Task View, is there another package you'd like to see replace it (on the Task View description).

![image](https://github.com/MarkEdmondson1234/searchConsoleR/assets/1372890/a0cf4409-1df1-47b3-aa86-3c3e1a6d2f97)

**Comment by MarkEdmondson1234** [comment]
Yes probably best to remove it until this package finds a new maintainer, I won’t have the time to look after it these days.

**Comment by wibeasley** [comment]
Gotcha.  To you or the future maintainer, please tell us if this gets back on CRAN and you think it is a good fit for the task view.
