### ISSUE TITLE
Can't Authenticate with gar_auth()

### ISSUE THREAD

**Issue by ericbrownaustin** [MarkEdmondson1234/searchConsoleR#9]
I am attempting to authenticate with gar_auth() and am having issues.  When I run `gar_auth(new_user=TRUE)` I get a browser prompt for authentication for bigqueryR rather than for searchconsoleR.  After hitting allow, I get an error:

```
  JSON fetch error: Insufficient Permission
In addition: Warning messages:
1: In retryRequest(do.call(request_type, args = arg_list, envir = asNamespace("httr"))) :
  Request Status Code: 403
2: In retryRequest(do.call(request_type, args = arg_list, envir = asNamespace("httr"))) :
  JSON fetch error: Insufficient Permission
3: In retryRequest(do.call(request_type, args = arg_list, envir = asNamespace("httr"))) :
  No retry attempted: Insufficient Permission
```
bigqueryR still works as expected.  I am running the 0.1.2 version.

**Comment by MarkEdmondson1234** [comment]
Ah yes, that means you need to set the scopes for BigQuery and Search Console. 

```
options("googleAuthR.scopes.selected" = c("https://www.googleapis.com/auth/webmasters",
                                          "https://www.googleapis.com/auth/bigquery"))

```

Make sure your project has those APIs activated in your google project too.  Some documentation around this is at: https://github.com/MarkEdmondson1234/googleAuthR
